# Generated by Django 4.2.5 on 2023-10-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.color')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.type')),
            ],
        ),
    ]
