# Generated by Django 4.2.5 on 2023-10-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='firestore_document_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
