# Generated by Django 4.2.5 on 2023-10-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
